### PR TITLE
🌻 Update environment (#5), thanks @hadley!

### PR DESCRIPTION
**Pull request by LucyMcGowan**
* Update environment (#5)

### CODE REVIEW

**Comment by LucyMcGowan** [comment]
@seankross, is it 👌 if I merge this?

**Comment by seankross** [comment]
@LucyMcGowan looks good to me!

**Comment by LucyMcGowan** [comment]
Ah, @seankross I spoke to soon 🙊 I don't think I have write access here 😂

**Comment by seankross** [comment]
I shall change that now!

**Comment by seankross** [comment]
@LucyMcGowan you are now all-powerful.

**Pull request merged**
